//For each command line argument the main process will launch a subprocess (type A).
//The A process will try to execute, in a new subprocess (type B), using one of the exec functions, the received argument.
//In case of failure, the process of type A, will send to his parent, using a pipe channel, the error code (errno value) 
//generated by the exec call. On success, the process A, will wait for process of type B and once finished it will transmit 
//to his parent the zero code, using the same pipe channel. The main process will print for each argument if the execution was 
//successful or not. Only for failed executions the error received code will be printed too.
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/wait.h>
#include <errno.h>
int main(int argc, char* argv[])
{	
	//if we do not have parameters in command line
	if (argc==1)
		printf("Please give some arguments in command line!\n");
	else
	{
		int c2p[2], p[2], i, status, a, b, isok, ok;
		for (i=1; i<argc, i++)
		{
			pipe(c2p);
			pipe(p);
			a=fork();
			if (a<0)
				{perror ("Error creating subprocess A\n");}
			else
			if (a==0)
			{
				b=fork();
				if (b<0)
					{perror("Error creating subprocess B\n");}
				else
				if (b==0)
				{
					//redirect the standard output because we are not interested in see the output of exec
					//just to know it the command was or not successfully executed
					dup2(p[1],1);
					close(p[0]);
					close(c2p[0]);
					
					//execute the command given as parameter in command line
					execlp(argv[i], argv[i], NULL);
					write(c2p[1], &errno, sizeof(int));
					exit(-1);
				}
				//wait for child
				waitpid(b, &status, 0);
				
				//WEXITSTATUS(status)==255(-1) if the command couldn't be executed and !=255 otherwise
				if (WEXITSTATUS(status)!=255)
				{
					isok=1;
					write(c2p[1], &isok, sizeof(int));
				}
				exit(0);
			}
			wait(0);
			close(p[1]);
			close(p[0]);
			close(c2p[1]);
			read(c2p[0], &ok, sizeof(int));
			if (ok==1)
				printf("The argument %s was executed\n", argv[i]);
			else
			{
				printf("The argument %s couldn't be executed\n", argv[i]);
				printf("Error code: %d\n", ok);
			}
		}
	}
	return 0;
}
		
